apiVersion: apps/v1
kind: Deployment
metadata:
  name: santosh-healthpod-deploy
  labels:
    app: santosh-healthcare-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: santosh-healthcare-app
  template:
    metadata:
      labels:
        app: santosh-healthcare-app
    spec:
      containers:
      - name: santosh-healthcare-container
        image: dskdockerid/santoshmedicurehealthcareimage:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: santosh-health-service
  labels:
    app: santosh-healthcare-app
spec:
  selector:
    app: santosh-healthcare-app

  type: NodePort
  ports:
  - nodePort: 32003
    port: 8082
    targetPort: 8082
